name: local_file_sharing
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0-323.0.dev

dependencies:
  encrypt: ^5.0.3
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  multicast_dns: ^0.3.2+7
  path_provider: ^2.1.3
  flutter_nearby_connections: ^1.1.2
  refena_flutter: ^2.1.1
  desktop_drop: ^0.4.4
  logger: ^2.3.0
  network_info_plus: ^5.0.3
  logging: ^1.2.0
  device_info_plus: ^10.1.0
  connectivity_plus: ^6.0.3
  dio: ^5.5.0+1
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
